import { ShoppingItem } from '@prisma/client';
import Head from 'next/head'
import { useState } from 'react';
import ItemModal from '../components/ItemModal';
import { trpc } from '../utils/trpc';

export default function IndexPage() {
  const { data, isLoading } = trpc.getAllItems.useQuery();
  const itemsData = data?.foundItems;
  
  const [items, setItems] = useState<ShoppingItem[]>(itemsData as ShoppingItem[]);
  const [modalOpen, setModalOpen] = useState<boolean>(false)

  if (!data || isLoading) return <p>Loading...</p>

  return (
    <div>
      <Head>
        <title>T3-Shopper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {modalOpen && <ItemModal setModalOpen={setModalOpen} setItems={setItems} />}
      
      <main className='mx-auto my-12 max-w-3xl'>
        <div className='flex justify-between'>
          <h2 className='text-2xl font-semibold'>My Shopping List</h2>
          <button
            type='button'
            className='bg-violet-500 text-white text-sm p-2 rounded-md transition hover:bg-violet-600'
            onClick={() => setModalOpen(true)}>
            Add shopping item
          </button>
        </div>

        <ul className='mt-4'>
          {items?.map(item => {
            return (
              <li
                key={item.id}
                className="flex justify-between items-center">
                <span>{item.name}</span>
              </li>
            )
          })}
        </ul>
      </main>

    </div>
  );
}
