import Head from 'next/head'
import { trpc } from '../utils/trpc';

export default function IndexPage() {
  const hello = trpc.hello.useQuery({ text: 'John' });

  if (!hello.data) {
    return <div>Loading...</div>;
  }

  return (
    <div>
      <Head>
        <title>T3-Shopper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-3xl font-bold underline">{hello.data.greeting}</p>
    </div>
  );
}
